# Generated by Django 4.1.6 on 2023-05-04 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(verbose_name='Nombre')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Ocupacion')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('idPelicula', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(verbose_name='Titulo')),
                ('fechaEstreno', models.DateField(null=True, verbose_name='Fecha de Estreno')),
                ('imdbUrl', models.URLField(verbose_name='URL en IMDB')),
                ('categorias', models.ManyToManyField(to='main.categoria')),
            ],
            options={
                'ordering': ('titulo', 'fechaEstreno'),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('edad', models.PositiveSmallIntegerField(help_text='Default', unique=True, verbose_name='Edad')),
                ('sexo', models.CharField(help_text='Default', max_length=1, verbose_name='Sexo')),
                ('codigoPostal', models.IntegerField(max_length=6, verbose_name='Código Postal')),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ocupacion')),
            ],
            options={
                'ordering': ('ocupacion',),
            },
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(help_text='Default', verbose_name='Puntuacion')),
                ('idPelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pelicula')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
            ],
            options={
                'ordering': ('idPelicula', 'idUsuario'),
            },
        ),
        migrations.AddField(
            model_name='pelicula',
            name='puntuaciones',
            field=models.ManyToManyField(through='main.Puntuacion', to='main.usuario'),
        ),
    ]
